### ISSUE TITLE
App crash on /register endpoint

### ISSUE THREAD

**Issue by canatac** [BREDFactory/flex-server#23]
When calling several times with same email, the app crashed :

```
Emitted 'error' event at:
2019-08-30T10:45:39.165581+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:4730:13
2019-08-30T10:45:39.165583+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/utils.js:263:16
2019-08-30T10:45:39.165584+00:00 app[web.1]:     at model.$__save.error (/app/node_modules/mongoose/lib/model.js:473:7)
2019-08-30T10:45:39.165586+00:00 app[web.1]:     at /app/node_modules/kareem/index.js:315:21
```

**Comment by canatac** [comment]
Non relevant
